/* Catálogo base — generado desde Cálculo_baterías_Alarmas.xlsx (hojas ocultas BD_DISPOSITIVOS, BD_CABLES, BD_BATERIAS).
 * Es la semilla inicial: el administrador lo edita desde la pestaña Administración.
 * Corrientes en mA a 24 VDC · resistencia de cable en Ω/km por conductor · baterías 12 V SLA (2 en serie = 24 V).
 * En la fase 2 estas listas pasan a tablas de Supabase. */
window.CATALOGO_BASE = {
  version: 2,
  actualizado: "2026-10-06",
  fabricantes: [
    {"id": "simplex", "nombre": "SIMPLEX"},
    {"id": "notifier", "nombre": "NOTIFIER"},
    {"id": "siemens", "nombre": "SIEMENS"},
    {"id": "generico", "nombre": "GENÉRICO"}
  ],
  dispositivos: [
    {"id": "d01", "fabricante": "simplex", "modelo": "4100ES", "tag": "FACP", "tipo": "Panel de control (FACP)", "descripcion": "PANEL PRINCIPAL 4100ES (CPU + fuente básica)", "iEspera": 425, "iAlarma": 735, "circuito": "SISTEMA", "obs": "Ficha 4100ES S4100-0031. Verificar según módulos instalados"},
    {"id": "d02", "fabricante": "simplex", "modelo": "4100-9600", "tag": "TRP", "tipo": "Transponder", "descripcion": "TRANSPONDER MODO LOCAL", "iEspera": 425, "iAlarma": 735, "circuito": "SISTEMA", "obs": "Ficha transponder 4100ES. Verificar configuración"},
    {"id": "d03", "fabricante": "simplex", "modelo": "4010ES", "tag": "FACP", "tipo": "Panel de control (FACP)", "descripcion": "PANEL 4010ES (CPU + fuente básica)", "iEspera": 250, "iAlarma": 425, "circuito": "SISTEMA", "obs": "Ficha S4010-0004. Verificar módulos"},
    {"id": "d04", "fabricante": "simplex", "modelo": "4098-9714", "tag": "SDH", "tipo": "Detector de humo", "descripcion": "DETECTOR HUMO FOTOELÉCTRICO TrueAlarm (IDNet)", "iEspera": 0.8, "iAlarma": 1, "circuito": "SLC", "obs": "Ficha S4098-0019"},
    {"id": "d05", "fabricante": "simplex", "modelo": "4098-9733", "tag": "SDT", "tipo": "Detector térmico", "descripcion": "DETECTOR TÉRMICO TrueAlarm (IDNet)", "iEspera": 0.8, "iAlarma": 1, "circuito": "SLC", "obs": "Ficha S4098-0019"},
    {"id": "d06", "fabricante": "simplex", "modelo": "4098-9755", "tag": "SD-DUCTO", "tipo": "Detector de humo de ducto", "descripcion": "SENSOR DE HUMO EN DUCTO (IDNet)", "iEspera": 0.8, "iAlarma": 1, "circuito": "SLC", "obs": "Ficha S4098-0024"},
    {"id": "d07", "fabricante": "simplex", "modelo": "4098-9770", "tag": "CO", "tipo": "Detector de CO", "descripcion": "BASE + SENSOR CO", "iEspera": 0.8, "iAlarma": 1, "circuito": "SLC", "obs": "Verificar ficha; base sonora suma consumo NAC"},
    {"id": "d08", "fabricante": "simplex", "modelo": "4099-9003", "tag": "EM", "tipo": "Estación manual", "descripcion": "ESTACIÓN MANUAL DIRECCIONABLE", "iEspera": 0.8, "iAlarma": 1, "circuito": "SLC", "obs": "Ficha S4099-0006"},
    {"id": "d09", "fabricante": "simplex", "modelo": "4090-9001", "tag": "AIM", "tipo": "Módulo de monitoreo", "descripcion": "MÓDULO DE MONITOREO IDNet", "iEspera": 0.8, "iAlarma": 1, "circuito": "SLC", "obs": "Ficha S4090-0011"},
    {"id": "d10", "fabricante": "simplex", "modelo": "4090-9002", "tag": "AOM", "tipo": "Módulo de control (salida)", "descripcion": "MÓDULO RELAY IDNet", "iEspera": 8, "iAlarma": 5, "circuito": "SLC", "obs": "Valor histórico Sinergia; verificar S4090-0011"},
    {"id": "d11", "fabricante": "simplex", "modelo": "4090-9101", "tag": "ZAM", "tipo": "Módulo de zona", "descripcion": "MÓDULO ADAPTADOR DE ZONA", "iEspera": 8, "iAlarma": 5, "circuito": "SLC", "obs": "Verificar ficha S4090-0012"},
    {"id": "d12", "fabricante": "simplex", "modelo": "4090-9116", "tag": "ISO", "tipo": "Aislador de lazo", "descripcion": "MÓDULO/BASE AISLADOR DE LAZO", "iEspera": 0.5, "iAlarma": 0.5, "circuito": "SLC", "obs": "Verificar ficha"},
    {"id": "d13", "fabricante": "simplex", "modelo": "4906-9151", "tag": "ST-P 15cd", "tipo": "Estrobo de pared", "descripcion": "ESTROBO PARED TrueAlert 15 cd", "iEspera": 0, "iAlarma": 59, "circuito": "NAC", "obs": "Ficha S4906-0004 (regulado 16–33 V)"},
    {"id": "d14", "fabricante": "simplex", "modelo": "4906-9151", "tag": "ST-P 30cd", "tipo": "Estrobo de pared", "descripcion": "ESTROBO PARED TrueAlert 30 cd", "iEspera": 0, "iAlarma": 67, "circuito": "NAC", "obs": "Ficha S4906-0004"},
    {"id": "d15", "fabricante": "simplex", "modelo": "4906-9151", "tag": "ST-P 75cd", "tipo": "Estrobo de pared", "descripcion": "ESTROBO PARED TrueAlert 75 cd", "iEspera": 0, "iAlarma": 107, "circuito": "NAC", "obs": "Ficha S4906-0004"},
    {"id": "d16", "fabricante": "simplex", "modelo": "4906-9151", "tag": "ST-P 110cd", "tipo": "Estrobo de pared", "descripcion": "ESTROBO PARED TrueAlert 110 cd", "iEspera": 0, "iAlarma": 139, "circuito": "NAC", "obs": "Ficha S4906-0004"},
    {"id": "d17", "fabricante": "simplex", "modelo": "4906-9151", "tag": "ST-P 135cd", "tipo": "Estrobo de pared", "descripcion": "ESTROBO PARED TrueAlert 135 cd", "iEspera": 0, "iAlarma": 166, "circuito": "NAC", "obs": "Ficha S4906-0004"},
    {"id": "d18", "fabricante": "simplex", "modelo": "4906-9154", "tag": "ST-C 15cd", "tipo": "Estrobo de cielo", "descripcion": "ESTROBO CIELO TrueAlert 15 cd", "iEspera": 0, "iAlarma": 59, "circuito": "NAC", "obs": "Ficha S4906-0004"},
    {"id": "d19", "fabricante": "simplex", "modelo": "4906-9154", "tag": "ST-C 30cd", "tipo": "Estrobo de cielo", "descripcion": "ESTROBO CIELO TrueAlert 30 cd", "iEspera": 0, "iAlarma": 67, "circuito": "NAC", "obs": "Ficha S4906-0004"},
    {"id": "d20", "fabricante": "simplex", "modelo": "4906-9154", "tag": "ST-C 75cd", "tipo": "Estrobo de cielo", "descripcion": "ESTROBO CIELO TrueAlert 75 cd", "iEspera": 0, "iAlarma": 107, "circuito": "NAC", "obs": "Ficha S4906-0004"},
    {"id": "d21", "fabricante": "simplex", "modelo": "4906-9127", "tag": "AV-P 15cd", "tipo": "Bocina + estrobo de pared", "descripcion": "BOCINA+ESTROBO PARED 15 cd", "iEspera": 0, "iAlarma": 74, "circuito": "NAC", "obs": "Ficha S4906-0002"},
    {"id": "d22", "fabricante": "simplex", "modelo": "4906-9127", "tag": "AV-P 30cd", "tipo": "Bocina + estrobo de pared", "descripcion": "BOCINA+ESTROBO PARED 30 cd", "iEspera": 0, "iAlarma": 84, "circuito": "NAC", "obs": "Ficha S4906-0002"},
    {"id": "d23", "fabricante": "simplex", "modelo": "4906-9127", "tag": "AV-P 75cd", "tipo": "Bocina + estrobo de pared", "descripcion": "BOCINA+ESTROBO PARED 75 cd", "iEspera": 0, "iAlarma": 140, "circuito": "NAC", "obs": "Ficha S4906-0002"},
    {"id": "d24", "fabricante": "simplex", "modelo": "4906-9127", "tag": "AV-P 110cd", "tipo": "Bocina + estrobo de pared", "descripcion": "BOCINA+ESTROBO PARED 110 cd", "iEspera": 0, "iAlarma": 185, "circuito": "NAC", "obs": "Ficha S4906-0002"},
    {"id": "d25", "fabricante": "simplex", "modelo": "4902-9717", "tag": "SPK", "tipo": "Parlante", "descripcion": "PARLANTE HABITACIÓN (tap 1 W @25/70.7V)", "iEspera": 0, "iAlarma": 10, "circuito": "VOCEO", "obs": "Corriente ref. en 24V equiv.; potencia real por tap en amplificador"},
    {"id": "d26", "fabricante": "simplex", "modelo": "4904-9168", "tag": "ST-WRF", "tipo": "Estrobo direccionable (IDNAC)", "descripcion": "ESTROBO PARED 49VO-WRF direccionable", "iEspera": 0, "iAlarma": 60, "circuito": "IDNAC", "obs": "Verificar ficha 49 Series por candela"},
    {"id": "d27", "fabricante": "simplex", "modelo": "2081-9044", "tag": "EOL", "tipo": "Resistencia fin de línea", "descripcion": "RESISTENCIA FIN DE LÍNEA SLC/NAC", "iEspera": 0, "iAlarma": 0, "circuito": "NAC", "obs": "Sin consumo supervisión DC apreciable"},
    {"id": "d28", "fabricante": "simplex", "modelo": "BASE SONORA", "tag": "SB", "tipo": "Base sonora", "descripcion": "DETECTOR + BASE SONORA (habitaciones)", "iEspera": 1, "iAlarma": 130, "circuito": "FUENTE AUX", "obs": "Valor histórico Sinergia. Verificar ficha de base sonora usada"},
    {"id": "d29", "fabricante": "notifier", "modelo": "NFS2-3030", "tag": "FACP", "tipo": "Panel de control (FACP)", "descripcion": "PANEL NFS2-3030 (CPU-3030 + display)", "iEspera": 210, "iAlarma": 375, "circuito": "SISTEMA", "obs": "Ficha DN-7080. Sumar lazos LCM/LEM y fuente"},
    {"id": "d30", "fabricante": "notifier", "modelo": "NFS-320", "tag": "FACP", "tipo": "Panel de control (FACP)", "descripcion": "PANEL NFS-320", "iEspera": 120, "iAlarma": 220, "circuito": "SISTEMA", "obs": "Ficha DN-7112. Verificar accesorios"},
    {"id": "d31", "fabricante": "notifier", "modelo": "FSP-951", "tag": "SDH", "tipo": "Detector de humo", "descripcion": "DETECTOR HUMO FOTOELÉCTRICO FlashScan", "iEspera": 0.3, "iAlarma": 6.5, "circuito": "SLC", "obs": "Ficha DN-60735; LED alarma"},
    {"id": "d32", "fabricante": "notifier", "modelo": "FST-951", "tag": "SDT", "tipo": "Detector térmico", "descripcion": "DETECTOR TÉRMICO FlashScan", "iEspera": 0.3, "iAlarma": 6.5, "circuito": "SLC", "obs": "Ficha DN-60737"},
    {"id": "d33", "fabricante": "notifier", "modelo": "DNR + FSP-951R", "tag": "SD-DUCTO", "tipo": "Detector de humo de ducto", "descripcion": "DETECTOR DE HUMO EN DUCTO", "iEspera": 0.3, "iAlarma": 6.5, "circuito": "SLC", "obs": "Ficha DN-60054"},
    {"id": "d34", "fabricante": "notifier", "modelo": "NBG-12LX", "tag": "EM", "tipo": "Estación manual", "descripcion": "ESTACIÓN MANUAL DIRECCIONABLE", "iEspera": 0.23, "iAlarma": 5, "circuito": "SLC", "obs": "Ficha DN-6726"},
    {"id": "d35", "fabricante": "notifier", "modelo": "FMM-1", "tag": "AIM", "tipo": "Módulo de monitoreo", "descripcion": "MÓDULO DE MONITOREO", "iEspera": 0.375, "iAlarma": 5, "circuito": "SLC", "obs": "Ficha DN-6720"},
    {"id": "d36", "fabricante": "notifier", "modelo": "FZM-1", "tag": "ZAM", "tipo": "Módulo de zona", "descripcion": "MÓDULO INTERFAZ ZONA CONVENCIONAL", "iEspera": 0.3, "iAlarma": 5, "circuito": "SLC", "obs": "Ficha DN-6720; sumar consumo zona en 24V"},
    {"id": "d37", "fabricante": "notifier", "modelo": "FCM-1", "tag": "AOM", "tipo": "Módulo de control (salida)", "descripcion": "MÓDULO DE CONTROL", "iEspera": 0.35, "iAlarma": 6.5, "circuito": "SLC", "obs": "Ficha DN-6720"},
    {"id": "d38", "fabricante": "notifier", "modelo": "FRM-1", "tag": "RLY", "tipo": "Módulo relay", "descripcion": "MÓDULO RELAY", "iEspera": 0.23, "iAlarma": 6.5, "circuito": "SLC", "obs": "Ficha DN-6720"},
    {"id": "d39", "fabricante": "notifier", "modelo": "ISO-X", "tag": "ISO", "tipo": "Aislador de lazo", "descripcion": "MÓDULO AISLADOR DE LAZO", "iEspera": 0.45, "iAlarma": 0.45, "circuito": "SLC", "obs": "Ficha DN-6994"},
    {"id": "d40", "fabricante": "notifier", "modelo": "WFD (+FMM-1)", "tag": "WF", "tipo": "Interruptor de flujo", "descripcion": "INTERRUPTOR DE FLUJO (vía módulo monitor)", "iEspera": 0, "iAlarma": 0, "circuito": "IDC", "obs": "Contacto seco; consumo lo aporta el FMM-1"},
    {"id": "d41", "fabricante": "notifier", "modelo": "PIBV2", "tag": "VS", "tipo": "Supervisor de válvula", "descripcion": "SUPERVISOR VÁLVULA (vía módulo monitor)", "iEspera": 0, "iAlarma": 0, "circuito": "IDC", "obs": "Contacto seco; consumo lo aporta el FMM-1"},
    {"id": "d42", "fabricante": "notifier", "modelo": "SR 15cd", "tag": "ST-P 15cd", "tipo": "Estrobo de pared", "descripcion": "ESTROBO PARED SpectrAlert Advance 15 cd", "iEspera": 0, "iAlarma": 64, "circuito": "NAC", "obs": "Ficha System Sensor S-SR; verificar por sincronización"},
    {"id": "d43", "fabricante": "notifier", "modelo": "SR 30cd", "tag": "ST-P 30cd", "tipo": "Estrobo de pared", "descripcion": "ESTROBO PARED SpectrAlert Advance 30 cd", "iEspera": 0, "iAlarma": 80, "circuito": "NAC", "obs": "Ficha S-SR"},
    {"id": "d44", "fabricante": "notifier", "modelo": "SR 75cd", "tag": "ST-P 75cd", "tipo": "Estrobo de pared", "descripcion": "ESTROBO PARED SpectrAlert Advance 75 cd", "iEspera": 0, "iAlarma": 127, "circuito": "NAC", "obs": "Ficha S-SR"},
    {"id": "d45", "fabricante": "notifier", "modelo": "SR 110cd", "tag": "ST-P 110cd", "tipo": "Estrobo de pared", "descripcion": "ESTROBO PARED SpectrAlert Advance 110 cd", "iEspera": 0, "iAlarma": 167, "circuito": "NAC", "obs": "Ficha S-SR"},
    {"id": "d46", "fabricante": "notifier", "modelo": "P2R 15cd", "tag": "AV-P 15cd", "tipo": "Bocina + estrobo de pared", "descripcion": "BOCINA+ESTROBO PARED P2R 15 cd", "iEspera": 0, "iAlarma": 101, "circuito": "NAC", "obs": "Ficha S-P2R (bocina temporal alto dBA)"},
    {"id": "d47", "fabricante": "notifier", "modelo": "P2R 75cd", "tag": "AV-P 75cd", "tipo": "Bocina + estrobo de pared", "descripcion": "BOCINA+ESTROBO PARED P2R 75 cd", "iEspera": 0, "iAlarma": 164, "circuito": "NAC", "obs": "Ficha S-P2R"},
    {"id": "d48", "fabricante": "notifier", "modelo": "P2R 110cd", "tag": "AV-P 110cd", "tipo": "Bocina + estrobo de pared", "descripcion": "BOCINA+ESTROBO PARED P2R 110 cd", "iEspera": 0, "iAlarma": 204, "circuito": "NAC", "obs": "Ficha S-P2R"},
    {"id": "d49", "fabricante": "notifier", "modelo": "SPSR 15cd", "tag": "SPK+ST 15cd", "tipo": "Parlante + estrobo de pared", "descripcion": "PARLANTE+ESTROBO PARED SPSR 15 cd", "iEspera": 0, "iAlarma": 64, "circuito": "NAC+VOCEO", "obs": "Estrobo en NAC; potencia parlante por tap"},
    {"id": "d50", "fabricante": "notifier", "modelo": "SPSCR 15cd", "tag": "SPK+ST-C 15cd", "tipo": "Parlante + estrobo de cielo", "descripcion": "PARLANTE+ESTROBO CIELO SPSCR 15 cd", "iEspera": 0, "iAlarma": 64, "circuito": "NAC+VOCEO", "obs": "Ídem"},
    {"id": "d51", "fabricante": "notifier", "modelo": "FDU-80", "tag": "ANN", "tipo": "Anunciador remoto", "descripcion": "ANUNCIADOR REMOTO FDU-80", "iEspera": 40, "iAlarma": 40, "circuito": "RED/24VDC", "obs": "Ficha DN-6820"},
    {"id": "d52", "fabricante": "notifier", "modelo": "FCPS-24S8", "tag": "RPS", "tipo": "Fuente de poder remota", "descripcion": "FUENTE REMOTA 24VDC 8A", "iEspera": 145, "iAlarma": 145, "circuito": "SISTEMA", "obs": "Ficha DN-6927; consumo propio + cargador aparte"},
    {"id": "d53", "fabricante": "siemens", "modelo": "FC922/FC924", "tag": "FACP", "tipo": "Panel de control (FACP)", "descripcion": "PANEL CERBERUS PRO FC92x", "iEspera": 300, "iAlarma": 500, "circuito": "SISTEMA", "obs": "Ficha A6V10333558; verificar configuración"},
    {"id": "d54", "fabricante": "siemens", "modelo": "OP921", "tag": "SDH", "tipo": "Detector de humo", "descripcion": "DETECTOR HUMO FOTOELÉCTRICO", "iEspera": 0.3, "iAlarma": 0.6, "circuito": "SLC", "obs": "Ficha A6V10334396; LED alarma aparte"},
    {"id": "d55", "fabricante": "siemens", "modelo": "HI921", "tag": "SDT", "tipo": "Detector térmico", "descripcion": "DETECTOR TÉRMICO", "iEspera": 0.3, "iAlarma": 0.6, "circuito": "SLC", "obs": "Ficha A6V10334400"},
    {"id": "d56", "fabricante": "siemens", "modelo": "HMS-S", "tag": "EM", "tipo": "Estación manual", "descripcion": "ESTACIÓN MANUAL DIRECCIONABLE", "iEspera": 0.3, "iAlarma": 0.6, "circuito": "SLC", "obs": "Ficha A6V10334406"},
    {"id": "d57", "fabricante": "siemens", "modelo": "TRI-S", "tag": "AIM", "tipo": "Módulo de monitoreo", "descripcion": "MÓDULO DE MONITOREO 1 ENTRADA", "iEspera": 0.35, "iAlarma": 0.55, "circuito": "SLC", "obs": "Ficha A6V10334546"},
    {"id": "d58", "fabricante": "siemens", "modelo": "TRI-R", "tag": "RLY", "tipo": "Módulo relay", "descripcion": "MÓDULO RELAY", "iEspera": 0.35, "iAlarma": 0.55, "circuito": "SLC", "obs": "Ficha A6V10334546"},
    {"id": "d59", "fabricante": "siemens", "modelo": "ZW-MSI-10", "tag": "ISO", "tipo": "Aislador de lazo", "descripcion": "AISLADOR / INTERFAZ", "iEspera": 0.4, "iAlarma": 0.4, "circuito": "SLC", "obs": "Verificar ficha"},
    {"id": "d60", "fabricante": "siemens", "modelo": "SW-24 15cd", "tag": "ST-P 15cd", "tipo": "Estrobo de pared", "descripcion": "ESTROBO PARED 15 cd (línea SW)", "iEspera": 0, "iAlarma": 68, "circuito": "NAC", "obs": "Verificar ficha A6V vigente"},
    {"id": "d61", "fabricante": "siemens", "modelo": "SW-24 75cd", "tag": "ST-P 75cd", "tipo": "Estrobo de pared", "descripcion": "ESTROBO PARED 75 cd", "iEspera": 0, "iAlarma": 130, "circuito": "NAC", "obs": "Verificar ficha"},
    {"id": "d62", "fabricante": "siemens", "modelo": "HSW-24 15cd", "tag": "AV-P 15cd", "tipo": "Bocina + estrobo de pared", "descripcion": "BOCINA+ESTROBO PARED 15 cd", "iEspera": 0, "iAlarma": 105, "circuito": "NAC", "obs": "Verificar ficha"},
    {"id": "d63", "fabricante": "generico", "modelo": "—", "tag": "OTRO", "tipo": "Otro dispositivo", "descripcion": "OTRO DISPOSITIVO (digitar corrientes manualmente)", "iEspera": 0, "iAlarma": 0, "circuito": "—", "obs": "Editar corrientes en esta fila"}
  ],
  cables: [
    {"id": "c01", "fabricante": "BELDEN", "modelo": "5020UL", "awg": 12, "conductores": 2, "pantalla": "NO", "listado": "FPL", "rKm": 5.2, "uso": "NAC alta corriente", "obs": "Ficha Belden 5020UL (1.60 Ω/1000 ft)"},
    {"id": "c02", "fabricante": "BELDEN", "modelo": "5120UL", "awg": 14, "conductores": 2, "pantalla": "NO", "listado": "FPL", "rKm": 8.4, "uso": "NAC", "obs": "Ficha Belden 5120UL (2.55 Ω/1000 ft)"},
    {"id": "c03", "fabricante": "BELDEN", "modelo": "5220UL", "awg": 16, "conductores": 2, "pantalla": "NO", "listado": "FPLR", "rKm": 13.5, "uso": "SLC / IDC / NAC / 24VDC", "obs": "Ficha Belden 5220UL (4.10 Ω/1000 ft). Estándar simbología Sinergia"},
    {"id": "c04", "fabricante": "BELDEN", "modelo": "5320UL", "awg": 18, "conductores": 2, "pantalla": "NO", "listado": "FPLR", "rKm": 21, "uso": "SLC corto", "obs": "Ficha Belden 5320UL (6.40 Ω/1000 ft)"},
    {"id": "c05", "fabricante": "BELDEN", "modelo": "5220FL", "awg": 16, "conductores": 2, "pantalla": "SÍ", "listado": "FPLR", "rKm": 13.5, "uso": "VOCEO / RED COBRE", "obs": "Ficha Belden 5220FL, par apantallado"},
    {"id": "c06", "fabricante": "BELDEN", "modelo": "5222FL", "awg": 16, "conductores": 4, "pantalla": "SÍ", "listado": "FPLR", "rKm": 13.5, "uso": "RED (datos+audio)", "obs": "4×16 AWG con pantalla, un par datos / un par audio"},
    {"id": "c07", "fabricante": "BELDEN", "modelo": "9575", "awg": 16, "conductores": 2, "pantalla": "NO", "listado": "FPL", "rKm": 13.5, "uso": "SLC", "obs": "Ficha Belden 9575"},
    {"id": "c08", "fabricante": "WEST PENN", "modelo": "AQ225", "awg": 16, "conductores": 2, "pantalla": "NO", "listado": "FPLW (húmedo)", "rKm": 13.5, "uso": "EXTERIORES SLC/NAC/24VDC", "obs": "Ficha West Penn AQ225 Aquaseal. Verificar R exacta"},
    {"id": "c09", "fabricante": "WEST PENN", "modelo": "AQ294", "awg": 16, "conductores": 4, "pantalla": "SÍ", "listado": "FPLW (húmedo)", "rKm": 13.5, "uso": "EXTERIORES RED", "obs": "Ficha West Penn AQ294. Verificar R exacta"},
    {"id": "c10", "fabricante": "GENÉRICO", "modelo": "THHN-12", "awg": 12, "conductores": 2, "pantalla": "NO", "listado": "THHN en EMT", "rKm": 5.21, "uso": "NAC", "obs": "Tabla NEC Cap. 9 Tabla 8 (cobre, 75°C ajustar)"},
    {"id": "c11", "fabricante": "GENÉRICO", "modelo": "THHN-14", "awg": 14, "conductores": 2, "pantalla": "NO", "listado": "THHN en EMT", "rKm": 8.28, "uso": "NAC", "obs": "Tabla NEC Cap. 9 Tabla 8"},
    {"id": "c12", "fabricante": "GENÉRICO", "modelo": "THHN-16", "awg": 16, "conductores": 2, "pantalla": "NO", "listado": "THHN en EMT", "rKm": 13.17, "uso": "SLC/NAC", "obs": "Tabla NEC Cap. 9 Tabla 8"},
    {"id": "c13", "fabricante": "GENÉRICO", "modelo": "THHN-18", "awg": 18, "conductores": 2, "pantalla": "NO", "listado": "THHN en EMT", "rKm": 20.95, "uso": "SLC", "obs": "Tabla NEC Cap. 9 Tabla 8"}
  ],
  baterias: [
    {"id": "b01", "ah": 6.2, "refSimplex": "2081-9272", "refNotifier": "PS-1270 (7Ah)", "refGenerica": "12V 7Ah", "obs": "Gabinete panel pequeño"},
    {"id": "b02", "ah": 10, "refSimplex": "2081-9271", "refNotifier": "PS-12100", "refGenerica": "12V 10Ah", "obs": ""},
    {"id": "b03", "ah": 12.7, "refSimplex": "2081-9287", "refNotifier": "PS-12120 (12Ah)", "refGenerica": "12V 12Ah", "obs": "Verificar ref. Simplex exacta"},
    {"id": "b04", "ah": 18, "refSimplex": "2081-9274", "refNotifier": "PS-12180", "refGenerica": "12V 18Ah", "obs": ""},
    {"id": "b05", "ah": 25, "refSimplex": "2081-9275", "refNotifier": "PS-12260 (26Ah)", "refGenerica": "12V 25Ah", "obs": "Puede requerir gabinete de baterías"},
    {"id": "b06", "ah": 33, "refSimplex": "2081-9288", "refNotifier": "PS-12330", "refGenerica": "12V 33Ah", "obs": "Gabinete externo típico"},
    {"id": "b07", "ah": 50, "refSimplex": "2081-9296", "refNotifier": "PS-12500", "refGenerica": "12V 50Ah", "obs": "Gabinete externo + cargador verificar"},
    {"id": "b08", "ah": 110, "refSimplex": "—", "refNotifier": "PS-121100", "refGenerica": "12V 110Ah", "obs": "Solo con cargador externo listado"}
  ]
};
